# generated by gen_dags.py:
#   filename:  primes_between.py:
#   timestamp: 2025-07-15T12:53:47.303100

from airflow.sdk import Param, dag, task

from s2gos_server.services.local.testing import primes_between


@dag(
    "primes_between",
    dag_display_name="Prime Processor",
    description="Returns the list of prime numbers between a `min_val` and `max_val`. ",
    multiple_outputs=False,
    params={
        "min_val": Param(default=0, type="integer", title="Min Val", minimum=0.0),
        "max_val": Param(default=100, type="integer", title="Max Val", maximum=100.0),
    },
)
def primes_between_dag():
    @task
    def primes_between_task(params):
        return primes_between(**params)

    task_instance = primes_between_task()  # noqa: F841
