# generated by gen_dags.py:
#   filename:  primes_between.py:
#   timestamp: 2025-07-15T10:36:22.246784

from airflow.sdk import Param, dag, task

from s2gos_server.services.local.testing import primes_between


@dag(
    "primes_between",
    description="Returns the list of prime numbers between a `min_val` and `max_val`. ",
    multiple_outputs=False,
    params={
        "min_val": Param(minimum=0.0, type="integer", default=0),
        "max_val": Param(maximum=100.0, type="integer", default=100),
    },
)
def primes_between_dag():
    @task
    def primes_between_task(params):
        return primes_between(**params)

    task_instance = primes_between_task()  # noqa: F841
