# generated by gen_dags.py:
#   filename:  return_base_model.py:
#   timestamp: 2025-07-15T13:16:40.238653

from airflow.sdk import Param, dag, task

from s2gos_server.services.local.testing import return_base_model


@dag(
    "return_base_model",
    dag_display_name="BaseModel Test",
    description=None,
    params={
        "scene_spec": Param(
            type="object",
            title="SceneSpec",
            properties={"threshold": {"title": "Threshold", "type": "number"}},
            required=["threshold"],
        ),
    },
)
def return_base_model_dag():
    @task(multiple_outputs=False)
    def return_base_model_task(params):
        return return_base_model(**params)

    task_instance = return_base_model_task()  # noqa: F841


dag_instance = return_base_model_dag()  # noqa: F841
