# generated by gen_dags.py:
#   filename:  return_base_model.py:
#   timestamp: 2025-07-15T10:36:23.550524

from airflow.sdk import Param, dag, task

from s2gos_server.services.local.testing import return_base_model


@dag(
    "return_base_model",
    description=None,
    multiple_outputs=False,
    params={
        "scene_spec": Param(
            required=["threshold"],
            type="object",
            properties={"threshold": {"title": "Threshold", "type": "number"}},
        ),
    },
)
def return_base_model_dag():
    @task
    def return_base_model_task(params):
        return return_base_model(**params)

    task_instance = return_base_model_task()  # noqa: F841
