# generated by gen_dags.py:
#   filename:  simulate_scene.py:
#   timestamp: 2025-07-15T12:53:47.994924

from airflow.sdk import Param, dag, task

from s2gos_server.services.local.testing import simulate_scene


@dag(
    "simulate_scene",
    dag_display_name="Generate scene for testing",
    description="Simulate a set scene images slices for testing. Creates an xarray dataset with `periodicity` time slices and writes it as Zarr into a temporary location. Requires installed `dask`, `xarray`, and `zarr` packages.",
    multiple_outputs=False,
    params={
        "var_names": Param(
            default="a, b, c",
            type="string",
            title="Variable names",
            description="Comma-separated list of variable names.",
        ),
        "bbox": Param(
            default=[-180, -90, 180, 90],
            type="array",
            title="Bounding box",
            description="Bounding box in geographical coordinates.",
            format="bbox",
            items={"type": "number"},
            maxItems=4,
            minItems=4,
        ),
        "resolution": Param(
            default=0.5,
            type="number",
            title="Spatial resolution",
            description="Spatial resolution in degree.",
            maximum=1.0,
            minimum=0.01,
        ),
        "start_date": Param(
            default="2025-01-01", type="string", title="Start date", format="date"
        ),
        "end_date": Param(
            default="2025-02-01", type="string", title="End date", format="date"
        ),
        "periodicity": Param(
            default=1,
            type="integer",
            title="Periodicity",
            description="Size of time steps in days.",
            maximum=10.0,
            minimum=1.0,
        ),
        "output_path": Param(
            type="string",
            title="Output path",
            description="Local output path or URI.",
            nullable=True,
        ),
    },
)
def simulate_scene_dag():
    @task
    def simulate_scene_task(params):
        return simulate_scene(**params)

    task_instance = simulate_scene_task()  # noqa: F841
