# generated by gen_dags.py:
#   filename:  simulate_scene.py:
#   timestamp: 2025-07-15T10:36:22.891368

from airflow.sdk import Param, dag, task

from s2gos_server.services.local.testing import simulate_scene


@dag(
    "simulate_scene",
    description="Simulate a set scene images slices for testing. Creates an xarray dataset with `periodicity` time slices and writes it as Zarr into a temporary location. Requires installed `dask`, `xarray`, and `zarr` packages.",
    multiple_outputs=False,
    params={
        "var_names": Param(type="string", default="a, b, c"),
        "bbox": Param(
            maxItems=4,
            minItems=4,
            type="array",
            items={"type": "number"},
            format="bbox",
            default=[-180, -90, 180, 90],
        ),
        "resolution": Param(maximum=1.0, minimum=0.01, type="number", default=0.5),
        "start_date": Param(type="string", format="date", default="2025-01-01"),
        "end_date": Param(type="string", format="date", default="2025-02-01"),
        "periodicity": Param(maximum=10.0, minimum=1.0, type="integer", default=1),
        "output_path": Param(type="string", nullable=True),
    },
)
def simulate_scene_dag():
    @task
    def simulate_scene_task(params):
        return simulate_scene(**params)

    task_instance = simulate_scene_task()  # noqa: F841
