# generated by gen_dags.py:
#   filename:  sleep_a_while.py:
#   timestamp: 2025-07-24T15:06:10.425749

from airflow.sdk import Param, dag, task

from s2gos_server.services.local.testing import sleep_a_while


@dag(
    "sleep_a_while",
    dag_display_name="Sleep Processor",
    description="Sleeps for `duration` seconds. Fails on purpose if `fail` is `True`. Returns the effective amount of sleep in seconds.",
    params={
        "duration": Param(default=10.0, type="number", title="Duration"),
        "fail": Param(default=False, type="boolean", title="Fail"),
    },
    is_paused_upon_creation=False,
)
def sleep_a_while_dag():
    @task(multiple_outputs=False)
    def sleep_a_while_task(params):
        return sleep_a_while(**params)

    task_instance = sleep_a_while_task()  # noqa: F841


sleep_a_while_dag()
