# generated by gen_server.py:
#   filename:  service.py:
#   timestamp: 2025-06-24T20:37:40.732138

from abc import ABC, abstractmethod

from fastapi.responses import JSONResponse

from s2gos_common.models import (
    Capabilities,
    ConformanceDeclaration,
    JobInfo,
    JobList,
    JobResults,
    ProcessDescription,
    ProcessList,
    ProcessRequest,
)


class Service(ABC):
    @abstractmethod
    async def get_capabilities(self) -> JSONResponse | Capabilities:
        pass

    @abstractmethod
    async def get_conformance(self) -> ConformanceDeclaration | JSONResponse:
        pass

    @abstractmethod
    async def get_processes(self) -> ProcessList | JSONResponse:
        pass

    @abstractmethod
    async def get_process(self, process_id: str) -> ProcessDescription | JSONResponse:
        pass

    @abstractmethod
    async def execute_process(
        self, process_id: str, request: ProcessRequest
    ) -> JobInfo | JSONResponse:
        pass

    @abstractmethod
    async def get_jobs(self) -> JobList | JSONResponse:
        pass

    @abstractmethod
    async def get_job(self, job_id: str) -> JobInfo | JSONResponse:
        pass

    @abstractmethod
    async def dismiss_job(self, job_id: str) -> JobInfo | JSONResponse:
        pass

    @abstractmethod
    async def get_job_results(self, job_id: str) -> JobResults | JSONResponse:
        pass
