[project]
name = "s2gos-controller"
version = "0.2.0.dev1"
description = "S2GOS control layer comprising a gateway server and client"
requires-python = ">=3.11"

# --- Tool configuration

[tool.isort]
skip = [".idea", ".github", ".pixi", "htmlcov", "site"]
profile = "black"
line_length = 88
known_first_party = ["s2gos_client", "s2gos_server"]

[tool.black]
line-length = 88

[tool.ruff]
include = [
    "notebooks/**/*.py",
    "s2gos-client/src/**/*.py",
    "s2gos-server/src/**/*.py",
    "tools/**/*.py",
]

[tool.ruff.lint]
ignore = ["E501", "I001"]
isort = { relative-imports-order = "closest-to-furthest" }
per-file-ignores = { "*.ipynb" = ["E402"] }
select = ["I", "F", "E"]

[tool.coverage.report]
omit = []

[tool.mypy]
python_version = "3.12"
check_untyped_defs = true
disable_error_code = ["valid-type", "import-untyped"]
exclude = [
    "s2gos-client/tests",
    "s2gos-server/tests",
    "eozilla",
    "tools",
]

# --- Tool configuration: pixi

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64"]

[tool.pixi.dependencies]
# Combined sub-workspace dependencies
fastapi = "*"
httpx = "*"
pydantic = "*"
pydantic-settings = ">=2.12.0,<3"
pyyaml = "*"
typer = ">=0.26"
universal_pathlib = ">=0.3.8,<0.4"
uri-template = "*"
uvicorn = "*"
# IDE integration
pixi-pycharm = ">=0.0.11"
# Development & build tools
pip = "*"
hatch = "*"
# Build for publication
rattler-build = ">=0.48.1,<0.49"
twine = ">=6.2.0,<7"
# Code style & linting
isort = "*"
ruff = "*"
mypy = "*"
# Unit-testing
pytest = "*"
pytest-cov = "*"
# Notebooks
jupyter = "*"
matplotlib = ">=3.11.0,<4"
# Use cases testing
dask = "*"
xarray = "*"
zarr = "*"
# Needed in /tools
tomlkit = "*"  # to sync versions
# Documentation
mkdocs = "==1.6.1"
mkdocs-autorefs = ">=1.4.3,<1.5"
mkdocs-get-deps = ">=0.2,<0.3"
mkdocs-jupyter = ">=0.25.1,<0.26"
mkdocs-material = ">=9.7.1,<9.8"
mkdocs-material-extensions = ">=1.3.1,<1.4"
mkdocstrings = ">=1.0.0,<1.1"
mkdocstrings-python = ">=2.0.1,<2.1"
nbformat = ">=5.10.4,<5.11"
pygments = ">=2.19,<2.20"

[tool.pixi.pypi-dependencies]
# Airflow is only available on PyPI
apache-airflow-client = "==3.0.2"
# Workspace dependencies
s2gos-client = { path = "s2gos-client", editable = true }
s2gos-server = { path = "s2gos-server", editable = true }
# eozilla from PyPI (uncomment if eozilla from source is used)
cuiman = ">=0.2.0.dev1"
gavicore = ">=0.2.0.dev1"
procodile = ">=0.2.0.dev1"
wraptile = ">=0.2.0.dev1"
# eozilla from sources (uncomment if eozilla from PyPI is used)
#appligator = { path = "../eozilla/appligator", editable = true }
#cuiman = { path = "../eozilla/cuiman", editable = true }
#gavicore = { path = "../eozilla/gavicore", editable = true }
#procodile = { path = "../eozilla/procodile", editable = true }
#wraptile = { path = "../eozilla/wraptile", editable = true }
#appligator = ">=0.2.0.dev1"

########################## Tasks ###############################

# pixi run x

[tool.pixi.tasks]
format-ruff = "ruff format ."
format-isort = "isort ."
test-client = "pytest s2gos-client/tests"
test-server = "pytest s2gos-server/tests"
cov-report-html = "coverage html -d .cov-report && coverage report"
cov-report-xml = "coverage xml -o coverage.xml && coverage report"
cov-client = "pytest --cov s2gos-client/src/s2gos_client --cov-report= --cov-append s2gos-client/tests"
cov-server = "pytest --cov s2gos-server/src/s2gos_server --cov-report= --cov-append s2gos-server/tests"
check-client = "ruff check s2gos-client/src"
check-server = "ruff check s2gos-server/src"
typecheck = "mypy ."
gen-cli-docs = "python -m tools.gen_cli_docs"
sync-versions = "python tools.sync_versions"
doc-serve = "mkdocs serve"
doc-build = "mkdocs build"
jl = "jupyter-lab"

# pixi run format

[tool.pixi.tasks.format]
depends-on = ["format-isort", "format-ruff"]

# pixi run tests

[tool.pixi.tasks.tests]
depends-on = ["test-client", "test-server"]

# pixi run coverage / coverage-ci

[tool.pixi.tasks.coverage]
depends-on = ["cov-client", "cov-server", "cov-report-html"]

[tool.pixi.tasks.coverage-ci]
depends-on = ["cov-client", "cov-server", "cov-report-xml"]

# pixi run checks

[tool.pixi.tasks.checks]
depends-on = ["check-client", "check-server", "typecheck"]

# pixi run build

[tool.pixi.tasks.build]
depends-on = ["build-client", "build-server"]

[tool.pixi.tasks.build-client]
cwd = "s2gos-client"
cmd = "hatch build --clean"

[tool.pixi.tasks.build-server]
cwd = "s2gos-server"
cmd = "hatch build --clean"

# pixi run deploy

[tool.pixi.tasks.deploy]
depends-on = [
  "deploy-client",
  "deploy-server",
]

[tool.pixi.tasks.deploy-client]
cwd = "s2gos-client"
cmd = "python -m twine upload dist/*"

[tool.pixi.tasks.deploy-server]
cwd = "s2gos-server"
cmd = "python -m twine upload dist/*"

