name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    pixi-ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Checkout Eozilla
              uses: actions/checkout@v7
              with:
                  repository: eo-tools/eozilla
                  path: eozilla

            - name: Setup pixi
              uses: prefix-dev/setup-pixi@v0.10.0
              with:
                  pixi-version: v0.67.2
                  cache: true

            - name: Run checks
              run: pixi run checks

            - name: Run test & coverage
              run: pixi run coverage-ci

            - name: Upload coverage reports
              uses: codecov/codecov-action@v7
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: s2gos-dev/s2gos-controller
